### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by MAiNPRoToCoL** [rufuspollock/s3-bucket-listing#115]
Does this still work? Maybe AWS S3 updated something and broke it? Because I've tried to get this to work, following all the steps/configs for AWS S3 static website hosting and it's not working for me, won't list the files. Thanks.

**Comment by greenbreakfast** [comment]
@MAiNPRoToCoL I followed "2. Use Amazon S3 in website mode with URL navigation" from the readme with a few modifications to make it work.

First, I set my BUCKET_URL to `http://BUCKET.s3.amazonaws.com` instead of `https://BUCKET.s3-REGION.amazonaws.com`. That made it correctly grab the bucket XML file, but that gave me a 403 access forbidden error.

Second, I updated my bucket permissions to give 1) Object Ownership to Object writer and 2) give Object "List" and Bucket ACL "Read" to "Everyone":
<img width="1290" alt="Screen Shot 2023-04-13 at 11 31 46 AM" src="https://user-images.githubusercontent.com/6757320/231810564-f5b35fec-0c13-4eb8-919e-b76ccdbbab20.png">

And now it works fine

**Comment by rufuspollock** [comment]
FIXED. Thanks for the info @greenbreakfast

**Comment by greenbreakfast** [comment]
@rufuspollock could you please update the README with this info?

**Comment by rufuspollock** [comment]
@greenbreakfast best would be if you did a PR for it - would you mind?
